//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAppService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisment
    {
        public int Ad_ID { get; set; }
        public string Ad_Name { get; set; }
        public string Ad_Description { get; set; }
        public byte[] Ad_AddDataTime { get; set; }
        public Nullable<double> Ad_Price { get; set; }
        public Nullable<int> Ad_Services { get; set; }
        public Nullable<int> Ad_Status { get; set; }
        public Nullable<int> Ad_Location { get; set; }
        public Nullable<int> Ad_Questions { get; set; }
    }
}
