//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAppService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Advertisment()
        {
            this.QuestionToAdvertisment = new HashSet<QuestionToAdvertisment>();
            this.ServiceToAdvertisment = new HashSet<ServiceToAdvertisment>();
        }
    
        public int AdvertismentID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public Nullable<double> Budget { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionToAdvertisment> QuestionToAdvertisment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceToAdvertisment> ServiceToAdvertisment { get; set; }
    }
}
