//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAppService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageBox
    {
        public int MessageBoxID { get; set; }
        public string Message { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public byte Readed { get; set; }
        public int SenderID { get; set; }
        public int ReciverID { get; set; }
    
        public virtual User User { get; set; }
    }
}
