//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAppService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_Answers
    {
        public int A_ID { get; set; }
        public string A_Name { get; set; }
        public Nullable<int> A_Question_ID { get; set; }
    
        public virtual Questions Questions { get; set; }
    }
}
