//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAppService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Questions()
        {
            this.Q_Answers = new HashSet<Q_Answers>();
        }
    
        public int Question_ID { get; set; }
        public string Q_Name { get; set; }
        public Nullable<int> Q_Category_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Q_Answers> Q_Answers { get; set; }
        public virtual Questions_Category Questions_Category { get; set; }
        public virtual Advertisment Advertisment { get; set; }

        internal static object ToList()
        {
            throw new NotImplementedException();
        }
    }
}
