//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAppService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Services()
        {
            this.User_Profesion = new HashSet<User_Profesion>();
        }
    
        public int Service_ID { get; set; }
        public string Service_Name { get; set; }
        public Nullable<int> Service_Category_ID { get; set; }
        public Nullable<double> Service_Price { get; set; }
        public Nullable<int> Service_PMeasurment_ID { get; set; }
    
        public virtual Ad_Services Ad_Services { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual Price_Measurment Price_Measurment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Profesion> User_Profesion { get; set; }
    }
}
