//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAppService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int Service_ID { get; set; }
        public string Service_Name { get; set; }
        public Nullable<int> Service_Category_ID { get; set; }
        public Nullable<double> Service_Price { get; set; }
        public Nullable<int> Service_PMeasurment_ID { get; set; }
    
        public virtual Ad_Services Ad_Services { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual Price_Measurment Price_Measurment { get; set; }
    }
}
